FROM golang:1.25.1-alpine3.22 AS builder

ENV CGO_ENABLED=0

RUN apk add --no-cache upx

WORKDIR /app

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY main.go ./

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -trimpath -ldflags="-s -w" -o /go/bin/aris-api-tmpl \
    && upx --best --lzma /go/bin/aris-api-tmpl

FROM alpine:3.22

RUN apk add --no-cache tzdata curl \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV TZ=Asia/Shanghai

WORKDIR /app

COPY --from=builder /go/bin/aris-api-tmpl /app/aris-api-tmpl

EXPOSE 8080

ENTRYPOINT ["/app/aris-api-tmpl"]
CMD ["server", "start", "--host", "0.0.0.0", "--port", "8080"]
